name: Actualizar Precios Carburantes

on:
  schedule:
    - cron: '0 4 * * *' # In theory at 6 am CET, reality it happens around 1h or 2h later
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Descargar datos oficiales del Ministerio
        run: |
          mkdir -p docs
          curl -H "Accept: application/json" \
               -H "User-Agent: GitHub-Actions-PrecioCombustible" \
               -o docs/precios-carburantes.json \
               "https://sedeaplicaciones.minetur.gob.es/ServiciosRESTCarburantes/PreciosCarburantes/EstacionesTerrestres/"

      - name: Commit y Push si hay cambios
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/precios-carburantes.json'
          message: 'Actualización automática de precios carburantes - ${{ format('{0,date,yyyy-MM-dd HH:mm}', github.event.repository.updated_at) }}'
          default_author: github_actions